server.port=8080
github.token=GITHUB_TOKEN
logging.level.com.githubreport=DEBUG
logging.level.org.springframework.web=INFO
logging.level.reactor.netty=DEBUG
logging.level.org.springframework.web.reactive=DEBUG
spring.jackson.serialization.indent-output=true
spring.jackson.serialization.write-dates-as-timestamps=false
spring.codec.max-in-memory-size=20971520